controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    effort_controller:
          type: forward_command_controller/ForwardCommandController

effort_controller:
  ros__parameters:
    joints:
      - wheel_left_joint
      - wheel_right_joint
    interface_name: effort